/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.stockmaster.stockmasterdb.view;

import br.com.stockmaster.stockmasterdb.classes.Supplier;
import br.com.stockmaster.stockmasterdb.dao.SupplierDAO;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author leona
 */
public class SupplierEdit extends javax.swing.JFrame {
    SupplierDAO dao = new SupplierDAO();

int SupplierId;

    public SupplierEdit(int id) {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setExtendedState(MAXIMIZED_BOTH);
        FieldsUpdate(id);
        this.SupplierId = id;
        
    }
    
    private void FieldsUpdate(int id){
   Supplier s = dao.findById(id);
   nameField.setText(s.getName());
   cnpjField.setText(s.getTaxId());
   addressField.setText(s.getAddress());
   numberField.setText(s.getNumber());
   emailField.setText(s.getEmail());
   obsArea.setText(s.getNotes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelGradiente1 = new  br.com.stockmaster.stockmasterdb.swing.PanelGradiente();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lProduct = new javax.swing.JButton();
        cProduct = new javax.swing.JButton();
        lSupplier = new javax.swing.JButton();
        cCustomer = new javax.swing.JButton();
        lCustomer = new javax.swing.JButton();
        lEmployeer = new javax.swing.JButton();
        cEmployeer = new javax.swing.JButton();
        rEntry = new javax.swing.JButton();
        rSales = new javax.swing.JButton();
        rOut = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        numberField = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        addressField = new javax.swing.JTextField();
        cnpjField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        panelGradiente1.setPrimaryColor(new java.awt.Color(0, 153, 255));
        panelGradiente1.setSecondaryColor(new java.awt.Color(0, 153, 204));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("StockMaster");
        panelGradiente1.add(jLabel4);
        jLabel4.setBounds(0, 70, 260, 47);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("- ESTOQUE");
        panelGradiente1.add(jLabel5);
        jLabel5.setBounds(10, 470, 180, 24);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("- PRODUTOS");
        panelGradiente1.add(jLabel6);
        jLabel6.setBounds(10, 160, 180, 24);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("- FORNECEDORES");
        panelGradiente1.add(jLabel7);
        jLabel7.setBounds(10, 230, 180, 24);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("- CLIENTES");
        panelGradiente1.add(jLabel8);
        jLabel8.setBounds(10, 310, 180, 24);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("- FUNCIONÁRIO");
        panelGradiente1.add(jLabel9);
        jLabel9.setBounds(10, 390, 180, 24);

        lProduct.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lProduct.setText("Lista de Produtos");
        lProduct.setBorderPainted(false);
        lProduct.setContentAreaFilled(false);
        lProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lProductActionPerformed(evt);
            }
        });
        panelGradiente1.add(lProduct);
        lProduct.setBounds(10, 210, 200, 20);

        cProduct.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        cProduct.setText("Cadastro de Produtos");
        cProduct.setBorderPainted(false);
        cProduct.setContentAreaFilled(false);
        cProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProductActionPerformed(evt);
            }
        });
        panelGradiente1.add(cProduct);
        cProduct.setBounds(10, 190, 200, 20);

        lSupplier.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lSupplier.setText("Lista de Fornecedores");
        lSupplier.setBorderPainted(false);
        lSupplier.setContentAreaFilled(false);
        lSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lSupplierActionPerformed(evt);
            }
        });
        panelGradiente1.add(lSupplier);
        lSupplier.setBounds(10, 280, 200, 20);

        cCustomer.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        cCustomer.setText("Cadastro de Clientes");
        cCustomer.setBorderPainted(false);
        cCustomer.setContentAreaFilled(false);
        cCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCustomerActionPerformed(evt);
            }
        });
        panelGradiente1.add(cCustomer);
        cCustomer.setBounds(0, 340, 240, 20);

        lCustomer.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lCustomer.setText("Lista de Clientes");
        lCustomer.setBorderPainted(false);
        lCustomer.setContentAreaFilled(false);
        lCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lCustomerActionPerformed(evt);
            }
        });
        panelGradiente1.add(lCustomer);
        lCustomer.setBounds(0, 360, 200, 20);

        lEmployeer.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lEmployeer.setText("Lista de Funcionários");
        lEmployeer.setBorderPainted(false);
        lEmployeer.setContentAreaFilled(false);
        lEmployeer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lEmployeer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lEmployeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lEmployeerActionPerformed(evt);
            }
        });
        panelGradiente1.add(lEmployeer);
        lEmployeer.setBounds(0, 440, 200, 20);

        cEmployeer.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        cEmployeer.setText("Cadastro de Funcionário");
        cEmployeer.setBorderPainted(false);
        cEmployeer.setContentAreaFilled(false);
        cEmployeer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cEmployeer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cEmployeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEmployeerActionPerformed(evt);
            }
        });
        panelGradiente1.add(cEmployeer);
        cEmployeer.setBounds(0, 420, 240, 20);

        rEntry.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        rEntry.setText("Registro de Entrada de Estoque");
        rEntry.setBorderPainted(false);
        rEntry.setContentAreaFilled(false);
        rEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rEntry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEntryActionPerformed(evt);
            }
        });
        panelGradiente1.add(rEntry);
        rEntry.setBounds(0, 500, 240, 20);

        rSales.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        rSales.setText("Registro de Venda");
        rSales.setBorderPainted(false);
        rSales.setContentAreaFilled(false);
        rSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rSales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSalesActionPerformed(evt);
            }
        });
        panelGradiente1.add(rSales);
        rSales.setBounds(0, 540, 240, 20);

        rOut.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        rOut.setText("Registro de Saída de Estoque");
        rOut.setBorderPainted(false);
        rOut.setContentAreaFilled(false);
        rOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rOutActionPerformed(evt);
            }
        });
        panelGradiente1.add(rOut);
        rOut.setBounds(0, 520, 240, 20);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("- Cadastro de Fornecedores");
        panelGradiente1.add(jLabel13);
        jLabel13.setBounds(30, 260, 190, 18);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOME:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CNPJ: ");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ENDEREÇO: ");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("TELEFONE: ");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("EMAIL: ");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("OBSERVAÇÕES:");

        nameField.setBackground(new java.awt.Color(204, 204, 204));
        nameField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nameField.setForeground(new java.awt.Color(0, 0, 0));
        nameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        numberField.setBackground(new java.awt.Color(204, 204, 204));
        numberField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numberField.setForeground(new java.awt.Color(0, 0, 0));
        numberField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        returnButton.setBackground(new java.awt.Color(255, 102, 102));
        returnButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        returnButton.setText("VOLTAR");
        returnButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(0, 153, 51));
        registerButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registerButton.setText("SALVAR");
        registerButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        addressField.setBackground(new java.awt.Color(204, 204, 204));
        addressField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addressField.setForeground(new java.awt.Color(0, 0, 0));
        addressField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        cnpjField.setBackground(new java.awt.Color(204, 204, 204));
        cnpjField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cnpjField.setForeground(new java.awt.Color(0, 0, 0));
        cnpjField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        emailField.setBackground(new java.awt.Color(204, 204, 204));
        emailField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(0, 0, 0));
        emailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        obsArea.setBackground(new java.awt.Color(204, 204, 204));
        obsArea.setColumns(20);
        obsArea.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        obsArea.setForeground(new java.awt.Color(0, 0, 0));
        obsArea.setRows(5);
        jScrollPane1.setViewportView(obsArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberField)
                            .addComponent(addressField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnpjField)
                            .addComponent(nameField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(1, 1, 1)
                        .addComponent(emailField)))
                .addGap(125, 125, 125))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14))
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("EDITAR CADASTRO DE FORNECEDORES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rOutActionPerformed
    StockOutRegister rOut = new StockOutRegister();
    rOut.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_rOutActionPerformed

    private void rSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSalesActionPerformed
    SalesRegister rSale = new SalesRegister();
    rSale.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_rSalesActionPerformed

    private void rEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEntryActionPerformed
EntryRegister rEntry = new EntryRegister();
rEntry.setVisible(true);
this.dispose();
    }//GEN-LAST:event_rEntryActionPerformed

    private void cEmployeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEmployeerActionPerformed
    EmployerRegister rEmployer = new EmployerRegister();
rEmployer.setVisible(true);
this.dispose();
    }//GEN-LAST:event_cEmployeerActionPerformed

    private void lEmployeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lEmployeerActionPerformed
        // TODO add your handling code here:
        EmployerList lEmployer = new EmployerList();
lEmployer.setVisible(true);
this.dispose();
    }//GEN-LAST:event_lEmployeerActionPerformed

    private void lCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lCustomerActionPerformed
        // TODO add your handling code here:
        CustomerList lCustomer = new CustomerList();
lCustomer.setVisible(true);
this.dispose();
    }//GEN-LAST:event_lCustomerActionPerformed

    private void cCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCustomerActionPerformed
        // TODO add your handling code here:
        CustomerRegister rCustomer = new CustomerRegister();
rCustomer.setVisible(true);
this.dispose();
    }//GEN-LAST:event_cCustomerActionPerformed

    private void lSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lSupplierActionPerformed
        // TODO add your handling code here:
        SupplierList lSupplier = new SupplierList();
lSupplier.setVisible(true);
this.dispose();
    }//GEN-LAST:event_lSupplierActionPerformed

    private void cProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cProductActionPerformed
        // TODO add your handling code here:
        ProductsRegister rProduct = new ProductsRegister();
rProduct.setVisible(true);
this.dispose();
    }//GEN-LAST:event_cProductActionPerformed

    private void lProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lProductActionPerformed
        // TODO add your handling code here:
        ProductsList lProduct = new ProductsList();
lProduct.setVisible(true);
this.dispose();
    }//GEN-LAST:event_lProductActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
    String name = nameField.getText();
    String cnpj = cnpjField.getText().replaceAll("[^0-9]", ""); // remove caracteres não numéricos
    String address = addressField.getText();
    String number = numberField.getText().replaceAll("[^0-9]", ""); // remove caracteres não numéricos
    String email = emailField.getText();
    String obs = obsArea.getText();

    // Verifica se todos os campos obrigatórios estão preenchidos
    if (name == null || name.trim().isEmpty()
        || cnpj == null || cnpj.trim().isEmpty()
        || address == null || address.trim().isEmpty()
        || number == null || number.trim().isEmpty()
        || email == null || email.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos corretamente!");
        return;
    }

    // Validação CNPJ
    if (!cnpj.matches("\\d{14}")) {
        JOptionPane.showMessageDialog(this, "CNPJ inválido! Deve conter 14 números.");
        return;
    }

    // Validação telefone
    if (!number.matches("\\d{10,11}")) {
        JOptionPane.showMessageDialog(this, "Número de telefone inválido! Deve conter 10 ou 11 dígitos.");
        return;
    }

    // Validação email simples
    if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,6}$")) {
        JOptionPane.showMessageDialog(this, "Email inválido! Informe um email no formato correto. (EX: email@gmail.com)");
        return;
    }

    // Atualiza o fornecedor
    Supplier supplier = dao.findById(SupplierId);
    if (supplier != null) {
        supplier.setName(name);
        supplier.setTaxId(cnpj);
        supplier.setAddress(address);
        supplier.setNumber(number);
        supplier.setEmail(email);
        supplier.setNotes(obs);
        dao.update(supplier);

        JOptionPane.showMessageDialog(this, "Fornecedor atualizado com sucesso!");
    } else {
        JOptionPane.showMessageDialog(this, "Fornecedor não encontrado!");
    }                                        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
SupplierList list = new SupplierList();
list.setVisible(true);
this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton cCustomer;
    private javax.swing.JButton cEmployeer;
    private javax.swing.JButton cProduct;
    private javax.swing.JTextField cnpjField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lCustomer;
    private javax.swing.JButton lEmployeer;
    private javax.swing.JButton lProduct;
    private javax.swing.JButton lSupplier;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField numberField;
    private javax.swing.JTextArea obsArea;
    private  br.com.stockmaster.stockmasterdb.swing.PanelGradiente panelGradiente1;
    private javax.swing.JButton rEntry;
    private javax.swing.JButton rOut;
    private javax.swing.JButton rSales;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
